### ISSUE TITLE
'class PS4Controller' has no member named '________'

### ISSUE THREAD

**Issue by Xaxper** [aed3/PS4-esp32#23]
Hello, I am able to connect the ps4 controller to the esp32 successfully, but I cannot get any input from the controller due to the following: 
![Screenshot from 2021-08-05 16-39-51](https://user-images.githubusercontent.com/73912447/128379410-03fd3119-ab68-4f63-8b39-8dda2024a633.png)
I'm working on Linux, esp32 board version 1.0.2. I downloaded the zip and added the library via the sketch>include library>add .zip library.

**Comment by Xaxper** [comment]
Hello, my issue is resolved, I dont know where i got the functions from but they seem to not work with the library. the correct versions can be found here:
https://github.com/aed3/PS4-esp32/blob/d23311c8489f2538c8e49d6e39dc33b19e0edbcb/examples/PS4ReceiveData/PS4ReceiveData.ino
