### ISSUE TITLE
Problem with ESP32 Board Manager higher than 1.0.4

### ISSUE THREAD

**Issue by e32sp** [aed3/PS4-esp32#21]
I think espressif changed something in the bluetooth library. Its working with Board Manager Version 1.0.4, but not with 1.0.5 or 1.06:
libraries\PS4-esp32-master\ps4_gap.c.o:(.literal.gapInitService+0x18): undefined reference to `GAP_ConnOpen'
libraries\PS4-esp32-master\ps4_gap.c.o:(.literal.gapEventHandle+0xc): undefined reference to `GAP_ConnGetL2CAPCid'
libraries\PS4-esp32-master\ps4_gap.c.o:(.literal.gapEventHandle+0x10): undefined reference to `GAP_ConnBTRead'
libraries\PS4-esp32-master\ps4_gap.c.o:(.literal.gapSendHid+0x10): undefined reference to `GAP_ConnBTWrite'
libraries\PS4-esp32-master\ps4_gap.c.o: In function `gapInitService':
libraries\PS4-esp32-master\src/ps4_gap.c:48: undefined reference to `GAP_ConnOpen'
libraries\PS4-esp32-master\ps4_gap.c.o: In function `gapUpdateConnected':
libraries\PS4-esp32-master\src/ps4_gap.c:48: undefined reference to `GAP_ConnGetL2CAPCid'
libraries\PS4-esp32-master\src/ps4_gap.c:48: undefined reference to `GAP_ConnGetL2CAPCid'
libraries\PS4-esp32-master\ps4_gap.c.o: In function `gapEventHandle':
\Arduino\libraries\PS4-esp32-master\src/ps4_gap.c:48: undefined reference to `GAP_ConnBTRead'
libraries\PS4-esp32-master\ps4_gap.c.o: In function `gapSendHid':
\Arduino\libraries\PS4-esp32-master\src/ps4_gap.c:88: undefined reference to `GAP_ConnBTWrite'
collect2.exe: error: ld returned 1 exit status
exit status 1
Fehler beim Kompilieren für das Board WEMOS LOLIN32.

Maybe thats an easy fix. Thanks for this great code. Having a lot of fun with it.

**Comment by bechhansen** [comment]
Duplicate of https://github.com/aed3/PS4-esp32/issues/15

**Comment by philgin** [comment]
any workaround on this? I can't use 1.0.4 because of the Big Sur issue.
